name: georange
description: A package that helps with encoding geohashes, decoding
  geohashes,calculating distance between 2 points and generating latitudinal and
  longitudinal ranges as geohashes to help with the querying of databases
  (Tested on Firestore Only).
version: 0.8.0
homepage: https://github.com/cngeru/georange
environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  test: ^1.16.8
